create database bigbrew;

create table bigbrew.Categories (
  CategoryID INT PRIMARY KEY auto_increment,
  name VARCHAR(255)
);

insert into categories (name) values
('add ons'),
('fruit'),
('hot drinks'),
('ice coffee'),
('milktea'),
('praf');


CREATE TABLE bigbrew.products (
  ProductID INT PRIMARY KEY auto_increment,
  name VARCHAR(255),
  image varchar(255),
  price DECIMAL(10, 2),
  medio DECIMAL(10, 2),
  grande DECIMAL(10, 2),
  CategoryID INT,
  FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);

INSERT INTO products (name, image, price, medio, grande, categoryid) VALUES
('Pearl', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Crystal', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Cream Cheese', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Coffee Jelly', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Crushed Oreo', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Cream Puff', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Cheesecake', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Brown Sugar Jelly', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Hot Brusko', 'img/Hot Brusko.png','35', 'null', 'NULL', '3' ),
('Hot Choko', 'img/Hot Choco.png', '35', 'null', 'NULL', '3'),
('Hot Moca', 'img/Hot Moca.png', '35', 'null', 'NULL', '3'),
('Hot Macha', 'img/Hot Matcha.png', '35', 'null', 'NULL', '3'),
('Hot Karamel', 'img/Hot Karamel.png', '35', 'null', 'NULL', '3'),
('Moca', 'img/Mocha Praf.png', '49', 'null', 'NULL', '6'),
('Coffee Jelly', 'img/Coffee Jelly Praf.png', '49', 'null', 'NULL', '6'),
('Caramel Macch', 'img/NO PICTURE YET.png', '49', 'null', 'NULL','6'),
('Vanilla Coffee', 'img/Vanilla Coffee.png', '49', 'null', 'NULL', '6'),
('Cookies and Cream', 'img/NO PICTURE YET.png', '49', 'null', 'NULL', '6'),
('Cheesecake Cream', 'img/NO PICTURE YET.png', '49', 'null', 'NULL', '6'),
('Taro Cream', 'img/Taro Cream.png', '49', 'null', 'NULL', '6'),
('Matcha Cream', 'img/NO PICTURE YET.png', '49', 'null', 'NULL', '6'),
('Chocolate Cream', 'img/NO PICTURE YET.png', '49', 'null', 'NULL', '6'),
('Strawberry Cream', 'img/Strawberry Praf.png', '49', 'null', 'NULL', '6'),
('Kiwi', 'img/Kiwi.png', 'null', '29', '39', '2'),
('Lychee', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Green Apple', 'img/Green Apple Fruit Tea.png', 'null', '29', '39', '2'),
('Lemon', 'img/Lemon Fruit Tea.png', 'null', '29', '39', '2'),
('Honey Peach', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Mango', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Blueberry', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Strawberry', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Passion Fruit', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Water Melon', 'img/Watermelon.png', 'null', '29', '39', '2'),
('Kape Brusko', 'img/Kape Brusko.png', 'null', '29', '39', '4'),
('Kape Macch', 'img/NO PICTURE YET.png', 'null', '29', '39', '4'),
('Kape Moca', 'img/Kape Mocha.png', 'null', '29', '39', '4'),
('Kape Vanilla', 'img/Kape Vanilla.png', 'null', '29', '39', '4'),
('Kape Fudge', 'img/Kape Fudge.png', 'null', '29', '39', '4'),
('Kape Matcha', 'img/NO PICTURE YET.png', 'null', '29', '39', '4'),
('Kape Karamel', 'img/Kape Karamel.png', 'null', '29', '39', '4'),
('Taro', 'NO PICTURE YET.png', 'null', '29', '39', '4'),
('Okinawa', 'Okinawa.png', 'null', '29', '39', '5'),
('Winter Melon', 'NO PICTURE YET.png', 'null', '29', '39', '5'),
('Red Velvet', 'Red Velvet.png', 'null', '29', '39', '5'),
('Matcha', 'Matcha.png', 'null', '29', '39', '5'),
('Double Dutch', 'NO PICTURE YET.png', 'null', '29', '39', '5'),
('Cheesecake', 'NO PICTURE YET.png', 'null', '29', '39', '5'),
('Dark Choco', 'Milktea/Dark Choco.png', 'null', '29', '39', '5'),
('Choco Kisses', 'NO PICTURE YET.png', 'null', '29', '39', '5'),
('Chocolate', 'NO PICTURE YET.png', 'null', '29', '39', '5'),
('Salted Caramel', 'NO PICTURE YET.png', 'null', '29', '39', '5'),
('Cookies and Cream', 'NO PICTURE YET.png', 'null', '29', '39', '5'),
('Strawberry', 'NO PICTURE YET.png', 'null', '29', '39', '5');


CREATE TABLE bigbrew.products (
  ProductID INT PRIMARY KEY auto_increment,
  name VARCHAR(255),
  image varchar(255),
  price DECIMAL(10, 2),
  medio DECIMAL(10, 2),
  grande DECIMAL(10, 2),
  CategoryID INT,
  FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);

INSERT INTO products (name, image, price, medio, grande, categoryid) VALUES
('Pearl', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Crystal', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Cream Cheese', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Coffee Jelly', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Crushed Oreo', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Cream Puff', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Cheesecake', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Brown Sugar Jelly', 'img/NO PICTURE YET.png', '9', 'null', 'NULL', '1'),
('Hot Brusko', 'img/Hot Brusko.png','35', 'null', 'NULL', '3' ),
('Hot Choko', 'img/Hot Choco.png', '35', 'null', 'NULL', '3'),
('Hot Moca', 'img/Hot Moca.png', '35', 'null', 'NULL', '3'),
('Hot Macha', 'img/Hot Matcha.png', '35', 'null', 'NULL', '3'),
('Hot Karamel', 'img/Hot Karamel.png', '35', 'null', 'NULL', '3'),
('Moca', 'img/Mocha Praf.png', '49', 'null', 'NULL', '6'),
('Coffee Jelly', 'img/Coffee Jelly Praf.png', '49', 'null', 'NULL', '6'),
('Caramel Macch', 'img/NO PICTURE YET.png', '49', 'null', 'NULL','6'),
('Vanilla Coffee', 'img/Vanilla Coffee.png', '49', 'null', 'NULL', '6'),
('Cookies and Cream', 'img/NO PICTURE YET.png', '49', 'null', 'NULL', '6'),
('Cheesecake Cream', 'img/NO PICTURE YET.png', '49', 'null', 'NULL', '6'),
('Taro Cream', 'img/Taro Cream.png', '49', 'null', 'NULL', '6'),
('Matcha Cream', 'img/NO PICTURE YET.png', '49', 'null', 'NULL', '6'),
('Chocolate Cream', 'img/NO PICTURE YET.png', '49', 'null', 'NULL', '6'),
('Strawberry Cream', 'img/Strawberry Praf.png', '49', 'null', 'NULL', '6'),
('Kiwi', 'img/Kiwi.png', 'null', '29', '39', '2'),
('Lychee', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Green Apple', 'img/Green Apple Fruit Tea.png', 'null', '29', '39', '2'),
('Lemon', 'img/Lemon Fruit Tea.png', 'null', '29', '39', '2'),
('Honey Peach', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Mango', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Blueberry', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Strawberry', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Passion Fruit', 'img/NO PICTURE YET.png', 'null', '29', '39', '2'),
('Water Melon', 'img/Watermelon.png', 'null', '29', '39', '2'),
('Kape Brusko', 'img/Kape Brusko.png', 'null', '29', '39', '4'),
('Kape Macch', 'img/NO PICTURE YET.png', 'null', '29', '39', '4'),
('Kape Moca', 'img/Kape Mocha.png', 'null', '29', '39', '4'),
('Kape Vanilla', 'img/Kape Vanilla.png', 'null', '29', '39', '4'),
('Kape Fudge', 'img/Kape Fudge.png', 'null', '29', '39', '4'),
('Kape Matcha', 'img/NO PICTURE YET.png', 'null', '29', '39', '4'),
('Kape Karamel', 'img/Kape Karamel.png', 'null', '29', '39', '4'),
('Taro', 'img/NO PICTURE YET.png', 'null', '29', '39', '4'),
('Okinawa', 'img/Okinawa.png', 'null', '29', '39', '5'),
('Winter Melon', 'img/NO PICTURE YET.png', 'null', '29', '39', '5'),
('Red Velvet', 'img/Red Velvet.png', 'null', '29', '39', '5'),
('Matcha', 'img/Matcha.png', 'null', '29', '39', '5'),
('Double Dutch', 'img/NO PICTURE YET.png', 'null', '29', '39', '5'),
('Cheesecake', 'img/NO PICTURE YET.png', 'null', '29', '39', '5'),
('Dark Choco', 'img/Milktea/Dark Choco.png', 'null', '29', '39', '5'),
('Choco Kisses', 'img/NO PICTURE YET.png', 'null', '29', '39', '5'),
('Chocolate', 'img/NO PICTURE YET.png', 'null', '29', '39', '5'),
('Salted Caramel', 'img/NO PICTURE YET.png', 'null', '29', '39', '5'),
('Cookies and Cream', 'img/NO PICTURE YET.png', 'null', '29', '39', '5'),
('Strawberry', 'img/NO PICTURE YET.png', 'null', '29', '39', '5');
